<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemalocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.lambdaisland</groupId>
  <artifactId>clj-slack</artifactId>
  <version>0.2.147</version>
  <name>clj-slack</name>
  <description>Slack toolbox</description>
  <url>https://github.com/GaiwanTeam/clj-slack</url>
  <inceptionYear>2021</inceptionYear>
  <organization>
    <name>Lambda Island</name>
    <url>https://lambdaisland.com</url>
  </organization>
  <properties>
    <project class="build sourceEncoding">UTF-8</project>
  </properties>
  <licenses>
    <license>
      <name>Eclipse Public License 1.0</name>
      <url>https://www.eclipse.org/legal/epl-v10.html</url>
    </license>
  </licenses>
  <scm>
    <url>https://github.com/GaiwanTeam/clj-slack</url>
    <connection>scm:git:git://github.com/GaiwanTeam/clj-slack.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/GaiwanTeam/clj-slack.git</developerConnection>
    <tag>44e944cd412fd5c9fdce985f068597144890b21f</tag>
  </scm>
  <dependencies>
    <dependency>
      <groupId>org.clojure</groupId>
      <artifactId>clojure</artifactId>
      <version>1.12.5</version>
    </dependency>
    <dependency>
      <groupId>com.lambdaisland</groupId>
      <artifactId>glogi</artifactId>
      <version>1.4.177</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jcl-over-slf4j</artifactId>
      <version>2.0.18</version>
    </dependency>
    <dependency>
      <groupId>io.pedestal</groupId>
      <artifactId>pedestal.log</artifactId>
      <version>0.8.1</version>
    </dependency>
    <dependency>
      <groupId>hato</groupId>
      <artifactId>hato</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jul-to-slf4j</artifactId>
      <version>2.0.18</version>
    </dependency>
    <dependency>
      <groupId>clojure.java-time</groupId>
      <artifactId>clojure.java-time</artifactId>
      <version>1.4.3</version>
    </dependency>
    <dependency>
      <groupId>org.java-websocket</groupId>
      <artifactId>Java-WebSocket</artifactId>
      <version>1.6.0</version>
    </dependency>
    <dependency>
      <groupId>com.lambdaisland</groupId>
      <artifactId>config</artifactId>
      <version>0.15.56</version>
    </dependency>
    <dependency>
      <groupId>com.lambdaisland</groupId>
      <artifactId>cli</artifactId>
      <version>1.30.130</version>
    </dependency>
    <dependency>
      <groupId>metosin</groupId>
      <artifactId>jsonista</artifactId>
      <version>1.0.0</version>
    </dependency>
    <dependency>
      <groupId>lambdaisland</groupId>
      <artifactId>uri</artifactId>
      <version>1.19.155</version>
    </dependency>
    <dependency>
      <groupId>com.cnuernber</groupId>
      <artifactId>charred</artifactId>
      <version>1.041</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.5.38</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>log4j-over-slf4j</artifactId>
      <version>2.0.18</version>
    </dependency>
  </dependencies>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <resources>
      <resource>
        <directory>src</directory>
      </resource>
      <resource>
        <directory>resources</directory>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.2.0</version>
        <configuration>
          <archive>
            <manifestEntries>
              <git-revision>44e944cd412fd5c9fdce985f068597144890b21f</git-revision>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-gpg-plugin</artifactId>
        <version>1.6</version>
        <executions>
          <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
              <goal>sign</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <repositories>
    <repository>
      <id>clojars</id>
      <url>https://repo.clojars.org/</url>
    </repository>
  </repositories>
  <distributionManagement>
    <repository>
      <id>clojars</id>
      <name>Clojars repository</name>
      <url>https://clojars.org/repo</url>
    </repository>
  </distributionManagement>
</project>